<!DOCTYPE html>
<html>
<head>
    <title>Ticket Report</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .header { text-align: center; margin-bottom: 30px; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Helpdesk Ticket Report</h1>
        <p>Generated on: {{ $date }}</p>
        @if(isset($filters['start_date']) || isset($filters['end_date']))
            <p>Period: {{ $filters['start_date'] ?? '...' }} to {{ $filters['end_date'] ?? '...' }}</p>
        @endif
    </div>

    <table>
        <thead>
            <tr>
                <th>Ticket ID</th>
                <th>Requestor</th>
                <th>Category</th>
                <th>Urgency</th>
                <th>Status</th>
                <th>Created At</th>
            </tr>
        </thead>
        <tbody>
            @foreach($tickets as $ticket)
                <tr>
                    <td>{{ $ticket->ticket_id }}</td>
                    <td>{{ $ticket->user->name }}</td>
                    <td>{{ $ticket->categoryCode->name ?? $ticket->category }}</td>
                    <td>{{ $ticket->urgencyCode->name ?? $ticket->urgency }}</td>
                    <td>{{ $ticket->statusCode->name ?? $ticket->status }}</td>
                    <td>{{ $ticket->created_at->format('d M Y') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by {{ config('app.name') }}
    </div>
</body>
</html>
